# Autogenerated runCitrus.R File
# Author: Robert Bruggner / bruggner@stanford.edu
# Compatible with Citrus version 0.8

rm(list = ls())
library("citrus",lib.loc=NULL)

# Use this line to limit the number of threads used by clustering
# Rclusterpp.setThreads(1);
options("mc.cores"=1);

family = "classification"

# Change if you want to run from command line
# dataDirectory = "../"
dataDirectory = "/Users/gosia/Dropbox/UZH/carsten_cytof/CK_2016-06-23_01/0_citrus/relabeled_base"

outputDirectory = file.path(dataDirectory,"citrusOutput")



clusteringColumns = c("Yb174Di", "Yb170Di", "Gd155Di", "Nd145Di", "Nd146Di", "Gd160Di", "Eu153Di", "Yb176Di", "Yb172Di", "Ho165Di", "Bi209Di", "Tm169Di", "Yb171Di")

transformColumns = c("Yb174Di", "Yb170Di", "Gd155Di", "Nd145Di", "Nd146Di", "Gd160Di", "Eu153Di", "Yb176Di", "Yb172Di", "Ho165Di", "Bi209Di", "Tm169Di", "Yb171Di")
transformCofactor = 5

scaleColumns = c(NULL)


minimumClusterSizePercent = 0.05
modelTypes = c("pamr")
fileSampleSize = 1000
nFolds = 1
featureType = c("abundances")
fileList = data.frame(defaultCondition=c("Base_Live_CK_Panel1_BASE_2016-06-23_1_live_NR1.fcs","Base_Live_CK_Panel1_BASE_2016-06-23_1_live_NR2.fcs","Base_Live_CK_Panel1_BASE_2016-06-23_1_live_NR3.fcs","Base_Live_CK_Panel1_BASE_2016-06-23_1_live_NR4.fcs","Base_Live_CK_Panel1_BASE_2016-06-23_1_live_NR5.fcs","Base_Live_CK_Panel1_BASE_2016-06-23_1_live_R1.fcs","Base_Live_CK_Panel1_BASE_2016-06-23_1_live_R2.fcs","Base_Live_CK_Panel1_BASE_2016-06-23_1_live_R3.fcs","Base_Live_CK_Panel1_BASE_2016-06-23_1_live_R4.fcs","Base_Live_CK_Panel1_BASE_2016-06-23_1_live_R5.fcs"))
labels = as.factor(c("NR","NR","NR","NR","NR","R","R","R","R","R"))



# results = citrus.full(
#   fileList=fileList,
#   labels=labels,
#   clusteringColumns=clusteringColumns,
#   dataDirectory=dataDirectory,
#   outputDirectory=outputDirectory,
#   family=family,
#   modelTypes=modelTypes,
#   nFolds=nFolds,
#   
#   fileSampleSize=fileSampleSize,
#   featureType=featureType,
#   minimumClusterSizePercent=minimumClusterSizePercent,
#   transformColumns=transformColumns,
#   transformCofactor=transformCofactor,
#   scaleColumns=scaleColumns
#   
# )
# 
# # plot results
# plot(results,outputDirectory)

# ==================================================================================================
# The following lines perform the same analysis as the citrus.full() function but broken down
# into component steps. This is may be more useful to run if you plan on running the clustering
# once but examining many endpoints, features, or minimum cluster sizes. You should uncomment 
# the clustering, feature extraction, regression, and plotting functionlines. 
# ==================================================================================================

# Read Data
citrus.combinedFCSSet = citrus.readFCSSet(dataDirectory,fileList,fileSampleSize,transformColumns,transformCofactor)

# Cluster all the data
citrus.foldClustering = citrus.clusterAndMapFolds(citrus.combinedFCSSet,clusteringColumns,labels,nFolds)

# OR load a previous clustering result. All other variables must be set by previous lines in runCitrus.R
#load(file.path(outputDirectory,"citrusClustering.rData"))

# Make vector of conditions for analysis. If comparing two conditions, should be
# two elements - first element is baseline condition and second is comparison condition.
conditions = colnames(fileList)[1]

# Build cluster features
citrus.foldFeatureSet = citrus.calculateFoldFeatureSet(citrus.foldClustering,citrus.combinedFCSSet,
  featureType=featureType,
  minimumClusterSizePercent=minimumClusterSizePercent,
  conditions=conditions
)

# Build regression models for each model type
citrus.regressionResults = mclapply(modelTypes,citrus.endpointRegress,citrus.foldFeatureSet=citrus.foldFeatureSet,labels=labels,family=family)

# Plot Results for each model
lapply(citrus.regressionResults,plot,outputDirectory=outputDirectory,citrus.foldClustering=citrus.foldClustering,citrus.foldFeatureSet=citrus.foldFeatureSet,citrus.combinedFCSSet=citrus.combinedFCSSet)


# ==================================================================================================
# Plot heatmaps 
# ==================================================================================================

library(plyr)
library(RColorBrewer)
library(pheatmap)

data <- citrus.combinedFCSSet$data
fcs_panel <- data.frame(fcs_colname = citrus.combinedFCSSet$fileChannelNames[[1]][[1]], Antigen = citrus.combinedFCSSet$fileReagentNames[[1]][[1]])
clusterAssignments <- clusterMembership <- citrus.foldClustering$allClustering$clusterMembership

cvPoints <- names(citrus.regressionResults[[1]]$differentialFeatures)


for(cvPoint in cvPoints){
  
  clusterIds <- as.numeric(citrus.regressionResults[[1]]$differentialFeatures[[cvPoint]]$clusters)
  
  ### Some cells belong to multiple clusters...!!!
  # cvClusters <- clusterMembership[clusterIds]
  # table(duplicated(unlist(cvClusters)))
  # all(clusterMembership[[9996]] %in% clusterMembership[[9997]])
  
  a <- lapply(1:length(clusterIds), function(i){
    # i = 1
    
    clusterId <- clusterIds[i]
    
    clusterDataList <- data[clusterAssignments[[clusterId]], clusteringColumns]
    
    a <- apply(clusterDataList, 2, median)
    
    return(a)
    
  })
  
  a <- do.call(rbind, a)
  
  rownames(a) <- clusterIds
  colnames(a) <- clusteringColumns
  
  
  mm <- match(clusteringColumns, fcs_panel$fcs_colname)
  colnames(a) <- fcs_panel$Antigen[mm]
  
  expr <- a
  color <- colorRampPalette(brewer.pal(n = 8, name = "YlGnBu"))(100)
  
  labels_row <- paste0(rownames(expr), " (", round(sapply(clusterMembership[clusterIds],length)/(length(clusterMembership)+1)*100, 2), "%)")
  labels_col <- colnames(expr)
  
  pheatmap(expr, color = color, cellwidth = 24, cellheight = 24, cluster_cols = FALSE, cluster_rows = FALSE, labels_col = labels_col, labels_row = labels_row, display_numbers = TRUE, number_color = "black", fontsize_number = 8, fontsize_row = 14, fontsize_col = 14, fontsize = 12, filename = file.path(outputDirectory, paste0("citrus_pheatmap-", cvPoint, ".pdf")))
  
}













# Large enough clusters
citrus.clustering <- citrus.foldClustering$allClustering

largeEnoughClusters = citrus.selectClusters(citrus.clustering)

sapply(clusterMembership[largeEnoughClusters],length)


# ==================================================================================================
# Have a look on the citrusClustering.rData object
# ==================================================================================================


load(paste0(dataDirectory, "/citrusOutput/citrusClustering.rData"))

o <- citrus.foldClustering$allClustering$clustering$order

mergeOrder <- citrus.foldClustering$allClustering$clustering$merge


clusterMembership <- citrus.foldClustering$allClustering$clusterMembership


table(sapply(clusterMembership, length))

length(clusterMembership)
length(unlist(clusterMembership))




# ==================================================================================================
### Examples

# Where the data lives
dataDirectory = file.path(system.file(package = "citrus"),"extdata","example1")

# Create list of files to be analyzed
fileList = data.frame("unstim"=list.files(dataDirectory,pattern=".fcs"))

# Read the data
citrus.combinedFCSSet = citrus.readFCSSet(dataDirectory,fileList)

# List of columns to be used for clustering
clusteringColumns = c("Red","Blue")

# Cluster data
citrus.clustering = citrus.cluster(citrus.combinedFCSSet,clusteringColumns)

# Plot clusters
citrus.plotClusters(clusterIds=c(19998,19997),clusterAssignments=citrus.clustering$clusterMembership,citrus.combinedFCSSet,clusteringColumns)


citrus.plotClusters(clusterIds=c(1, 2),clusterAssignments=citrus.clustering$clusterMembership,citrus.combinedFCSSet,clusteringColumns)



# Large enough clusters
largeEnoughClusters = citrus.selectClusters(citrus.clustering)

# Create graph for plotting
hierarchyGraph = citrus.createHierarchyGraph(citrus.clustering,selectedClusters=largeEnoughClusters)


# Create matrix of variables to plot (in this case, cluster medians)
clusterMedians = t(sapply(largeEnoughClusters,citrus:::.getClusterMedians,clusterAssignments=citrus.clustering$clusterMembership,data=citrus.combinedFCSSet$data,clusterCols=clusteringColumns))
rownames(clusterMedians) = largeEnoughClusters
colnames(clusterMedians) = clusteringColumns

# Plot Clustering Hierarchy - Uncomment and Specify an output file
citrus.plotClusteringHierarchy(outputFile="citrus.pdf",clusterColors=clusterMedians,graph=hierarchyGraph$graph,layout=hierarchyGraph$layout,plotSize=hierarchyGraph$plotSize)













