# Autogenerated runCitrus.R File
# Author: Robert Bruggner / bruggner@stanford.edu
# Compatible with Citrus version 0.8

# ==================================================================================================
# Prepare the FCS files
# ==================================================================================================

# library("citrus")
# citrus.checkFileParameterConsistencyUI()

### First, generate  panel3.csv file from CK_panels/panel3.csv


# library("cytofCore")
# cytofCore.updatePanel(fcsFolder = "/Users/gosia/Dropbox/UZH/carsten_cytof/CK_2016-06-23_03/0_citrus", templateFile = "/Users/gosia/Dropbox/UZH/carsten_cytof/CK_2016-06-23_03/0_citrus/panel3.csv")

### Split base and tx samples from relabeled/ into relabeled_base/ and relabeled_tx/ and remove HD samples

# ==================================================================================================
# Run citrus
# ==================================================================================================

library(gdata)
library(limma)
library(citrus)

rwd='/Users/gosia/Dropbox/UZH/carsten_cytof/CK_2016-06-23_03'
path_clustering_observables='030_heatmaps/23_03_pca1_clustering_observables.xls'
path_metadata='/Users/gosia/Dropbox/UZH/carsten_cytof/CK_metadata/metadata_23_03.xlsx'
citrus_outdir='citrusOutput_1000'
fileSampleSize=1000

# rwd='/Users/gosia/Dropbox/UZH/carsten_cytof/CK_2016-06-23_01'
# path_clustering_observables='030_heatmaps/23_01_pca1_clustering_observables.xls'
# path_metadata='/Users/gosia/Dropbox/UZH/carsten_cytof/CK_metadata/metadata_23_01.xlsx'


##############################################################################
# Read in the arguments
##############################################################################

rm(list = ls())

args <- (commandArgs(trailingOnly = TRUE))
for (i in 1:length(args)) {
  eval(parse(text = args[[i]]))
}

cat(args, fill = TRUE)

##############################################################################


setwd(rwd)

outdir <- citrus_outdir

if( !file.exists(outdir) ) 
  dir.create(outdir)


# ------------------------------------------------------------
# Load clustering_observables
# ------------------------------------------------------------

clustering_observables <- read.table(path_clustering_observables, header = TRUE, sep = "\t", as.is = TRUE)

clust_observ <- clustering_observables[clustering_observables$clustering_observable, "mass"]

# ------------------------------------------------------------
# Load metadata
# ------------------------------------------------------------

md <- read.xls(path_metadata, stringsAsFactors=FALSE)

# add more info about samples
cond_split <- strsplit2(md$condition, "_")
colnames(cond_split) <- c("day", "response")

md[, c("day", "response")] <- cond_split
md$response <- factor(md$response, levels = c("NR", "R", "HD"))
md$day <- factor(md$day, levels = c("base", "tx"))
md$patient_id <- factor(md$patient_id)


# ------------------------------------------------------------
# Set citrus parameters
# ------------------------------------------------------------

# Use this line to limit the number of threads used by clustering
# Rclusterpp.setThreads(1);
options("mc.cores"=1);

family = "classification"

dataDirectory = paste0(rwd, "/0_citrus/relabeled_base")

outputDirectory = file.path(dataDirectory, outdir)


clusteringColumns = clust_observ

transformColumns = clust_observ

transformCofactor = 5
scaleColumns = c(NULL)

minimumClusterSizePercent = 0.05
modelTypes = c("pamr")
fileSampleSize = fileSampleSize
nFolds = 1
featureType = c("abundances")


files_keep <- md$day == "base" & md$response %in% c("NR", "R")

fileList = data.frame(defaultCondition = md[files_keep, "filename"])
labels = factor(md[files_keep, "response"])



# results = citrus.full(
#   fileList=fileList,
#   labels=labels,
#   clusteringColumns=clusteringColumns,
#   dataDirectory=dataDirectory,
#   outputDirectory=outputDirectory,
#   family=family,
#   modelTypes=modelTypes,
#   nFolds=nFolds,
#   
#   fileSampleSize=fileSampleSize,
#   featureType=featureType,
#   minimumClusterSizePercent=minimumClusterSizePercent,
#   transformColumns=transformColumns,
#   transformCofactor=transformCofactor,
#   scaleColumns=scaleColumns
#   
# )
# 
# # plot results
# plot(results,outputDirectory)

# ==================================================================================================
# The following lines perform the same analysis as the citrus.full() function but broken down
# into component steps. This is may be more useful to run if you plan on running the clustering
# once but examining many endpoints, features, or minimum cluster sizes. You should uncomment 
# the clustering, feature extraction, regression, and plotting functionlines. 
# ==================================================================================================

# Read Data
citrus.combinedFCSSet = citrus.readFCSSet(dataDirectory,fileList,fileSampleSize,transformColumns,transformCofactor)

# Cluster all the data
citrus.foldClustering = citrus.clusterAndMapFolds(citrus.combinedFCSSet,clusteringColumns,labels,nFolds)

# OR load a previous clustering result. All other variables must be set by previous lines in runCitrus.R
#load(file.path(outputDirectory,"citrusClustering.rData"))

# Make vector of conditions for analysis. If comparing two conditions, should be
# two elements - first element is baseline condition and second is comparison condition.
conditions = colnames(fileList)[1]

# Build cluster features
citrus.foldFeatureSet = citrus.calculateFoldFeatureSet(citrus.foldClustering,citrus.combinedFCSSet,
  featureType=featureType,
  minimumClusterSizePercent=minimumClusterSizePercent,
  conditions=conditions
)

# Build regression models for each model type
citrus.regressionResults = mclapply(modelTypes,citrus.endpointRegress,citrus.foldFeatureSet=citrus.foldFeatureSet,labels=labels,family=family)

# Plot Results for each model
lapply(citrus.regressionResults,plot,outputDirectory=outputDirectory,citrus.foldClustering=citrus.foldClustering,citrus.foldFeatureSet=citrus.foldFeatureSet,citrus.combinedFCSSet=citrus.combinedFCSSet)


# ==================================================================================================
# Plot heatmaps 
# ==================================================================================================

library(plyr)
library(RColorBrewer)
library(pheatmap)

data <- citrus.combinedFCSSet$data
fcs_panel <- data.frame(fcs_colname = citrus.combinedFCSSet$fileChannelNames[[1]][[1]], Antigen = citrus.combinedFCSSet$fileReagentNames[[1]][[1]])
clusterAssignments <- clusterMembership <- citrus.foldClustering$allClustering$clusterMembership

cvPoints <- names(citrus.regressionResults[[1]]$differentialFeatures)


for(cvPoint in cvPoints){
  # cvPoint <- "cv.1se"
  print(cvPoint)
  
  cluster_tmp <- citrus.regressionResults[[1]]$differentialFeatures[[cvPoint]]
  
  if(class(cluster_tmp) == "character")
    clusterIds <- as.numeric(cluster_tmp["clusters"])
  if(class(cluster_tmp) == "list")
    clusterIds <- as.numeric(cluster_tmp$clusters)
  
  ### Some cells belong to multiple clusters...!!!
  # cvClusters <- clusterMembership[clusterIds]
  # table(duplicated(unlist(cvClusters)))
  # all(clusterMembership[[9996]] %in% clusterMembership[[9997]])
  
  a <- lapply(1:length(clusterIds), function(i){
    # i = 1
    
    clusterId <- clusterIds[i]
    
    clusterDataList <- data[clusterAssignments[[clusterId]], clusteringColumns]
    
    a <- apply(clusterDataList, 2, median)
    
    return(a)
    
  })
  
  a <- do.call(rbind, a)
  
  rownames(a) <- clusterIds
  colnames(a) <- clusteringColumns
  
  
  mm <- match(clusteringColumns, fcs_panel$fcs_colname)
  colnames(a) <- fcs_panel$Antigen[mm]
  
  expr <- a
  color <- colorRampPalette(brewer.pal(n = 8, name = "YlGnBu"))(100)
  
  labels_row <- paste0(rownames(expr), " (", round(sapply(clusterMembership[clusterIds],length)/(length(clusterMembership)+1)*100, 2), "%)")
  labels_col <- colnames(expr)
  
  pheatmap(expr, color = color, cellwidth = 24, cellheight = 24, cluster_cols = FALSE, cluster_rows = FALSE, labels_col = labels_col, labels_row = labels_row, display_numbers = TRUE, number_color = "black", fontsize_number = 8, fontsize_row = 14, fontsize_col = 14, fontsize = 12, filename = file.path(outputDirectory, paste0("citrus_pheatmap-", cvPoint, ".pdf")))
  
}













### Large enough clusters
# citrus.clustering <- citrus.foldClustering$allClustering
# 
# largeEnoughClusters = citrus.selectClusters(citrus.clustering)
# 
# sapply(clusterMembership[largeEnoughClusters],length)


# ==================================================================================================
# Have a look on the citrusClustering.rData object
# ==================================================================================================


# load(paste0(dataDirectory, "/citrusOutput/citrusClustering.rData"))
# 
# o <- citrus.foldClustering$allClustering$clustering$order
# 
# mergeOrder <- citrus.foldClustering$allClustering$clustering$merge
# 
# 
# clusterMembership <- citrus.foldClustering$allClustering$clusterMembership
# 
# 
# table(sapply(clusterMembership, length))
# 
# length(clusterMembership)
# length(unlist(clusterMembership))










################################
### 0_runCitrus.R done!
################################
